spring: 
  application:
    name: ldszuul
server:
  port: 1115
eureka:
  instance:
    prefer-ip-address: true
#    lease-renewal-interval-in-seconds: 5
#    lease-expiration-duration-in-seconds: 10
  client:
    serviceUrl:
      defaultZone: http://test:test@127.0.0.1:1110/eureka/
#    registry-fetch-interval-seconds: 5
zuul:
  sensitive-headers: null
  ignored-services: eureka,ldstrubine,configserver
  host:
    connect-timeout-millis: 4000
    connection-request-timeout-millis: 2000
ribbon: 
  eager-load:
    enabled: true
  ConnectTimeout: 3000
  ReadTimeout: 10000
  SocketTimeout:  1000
management:
  endpoints:
    web:
      exposure:
        include: routes,filters,details
  endpoint:
    shutdown:
      enabled: false 
logging:
  level:
    root: INFO